### ISSUE TITLE
manage.py get_dropbox_token: error: unrecognized arguments: [--settings=test_settings]

### ISSUE THREAD

**Issue by Rahu-ju** [zuck/django-dropbox-storage#1]
@ZUCK, When i run the following command it raises that error,
`python manage.py get_dropbox_token [--settings=test_settings]`
Please, let me know, what's going on?

**Comment by zahidtokur** [comment]
I know you posted this a while ago but in case you still need an answer here is what worked for me:

I ran `python manage.py get_dropbox_token` and it raised an error :

`auth_code = raw_input("Enter the authorization code here: ").strip()`
`NameError: name 'raw_input' is not defined`

Then I edited get_dropbox_token.py file inside django_dropbox_storage\management\commands folder, changed `raw_input` to `input` then ran the  `python manage.py get_dropbox_token` command again and it worked.

**Comment by loictessier** [comment]
For me I just removed the brackets:
`python manage.py get_dropbox_token --settings=test_settings`

**Comment by zuck** [comment]
Thank you all for signaling this issue!

@zahidtokur which version of Django are you targetting? Can you please provide a PR?

@loictessier Same, which version of Django are you using?

**Comment by zuck** [comment]
BTW, this is not a real issue. The square brackets are commonly used in tech docs to identify an **optional** argument.
