### ISSUE TITLE
No module named StringIO

### ISSUE THREAD

**Issue by adriankokai** [zuck/django-dropbox-storage#8]
I am receiving a ModuleNotFoundError when trying to use **django-dropbox-storage** as explained here: [](https://pypi.org/project/django-dropbox-storage/)

Exception Type: ModuleNotFoundError
Exception Value: No module named 'StringIO'
Exception Location: /app/.heroku/python/lib/python3.7/site-packages/django_dropbox_storage/storage.py, line 8, in <module>
Python version: 3.7.8

Locally on my machine, I changed line 8 in Exception Location to `from io import StringIO` and everything worked fine but I am not able to do likewise on Heroku server.

**Comment by zuck** [comment]
Fixed with e1df6cd41533dd5239706ba4cad36f7983e50521
